language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run --verbose --format=dot
  - vendor/bin/phpunit --verbose

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true